FROM ubuntu:18.04

RUN apt-get update && apt-get -y install sudo && apt-get -y install git

RUN apt-get -y install curl && apt-get -y install unzip

RUN mkdir -p /home/ubuntu

RUN useradd -d /home/ubuntu ubuntu

RUN usermod -aG sudo ubuntu

RUN chown -R ubuntu:ubuntu /home/ubuntu

RUN echo "ubuntu ALL=(ALL)NOPASSWD:ALL" >> /etc/sudoers

USER ubuntu

WORKDIR /home/ubuntu

RUN git clone https://github.com/libra/libra.git

ENTRYPOINT [ "sleep" ]

CMD ["1000"]